# This pipeline runs multiple stages
# release stage uses a 'special' deployment job
# this is a 'minumum template' to use in productuin

trigger:
- master # pipeline will run on new commits to specified branch

variables:
  subscriptionConnectionName: 'My subscription connection'
  subscriptionId: '6dca9329-fb22-46cb-826c-e26edc8a4840'
  poolName: 'Windows-latest'
  deploymeneLocation: 'NorwayEast'

pool:
  vmImage: $(poolName)

# normally build stages will build an application along with the infrastructure
stages:
  - stage: BUILD
    jobs:
    - job:
      displayName: 'copy templates as artifacts'
      steps:
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Pipeline.Workspace)'
            artifact: 'resourceTemplates'
            publishLocation: 'pipeline'

 # production scenarios often require a more complex test. In this case we verify the arm tempate 
  - stage: TEST
    jobs:
    - job:
      displayName: 'Verify ARM template'
      steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Subscription'
            azureResourceManagerConnection: $(subscriptionConnectionName)  #defined in variable
            subscriptionId: $(subscriptionId) #defined in variable
            location: $(deploymeneLocation) #defined in variable
            templateLocation: 'Linked artifact'
            csmFile: '$(Build.SourcesDirectory)/linked-nested/nested/azure.deploy.json' # path to the file you wan to deploy. could be url using csmFileLink
            csmParametersFile: '$(Build.SourcesDirectory)/linked-nested/nested/azure.deploy.parameters.json'
            deploymentMode: 'Validation'
            deploymentName: 'Validatingtemplate'
  
  - stage: RELEASE
    dependsOn: TEST # stage will not run if test fails
    jobs:
      - deployment: 'deployResources'
        displayName: 'Deploy azure resources'
        environment: 'arm-livestreams'
        pool:
         vmImage: $(poolName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: PowerShell@2
                  inputs:
                    targetType: 'inline'
                    script: |
                      cd $(Pipeline.Workspace)/resourceTemplates
                      dir
                - task: AzureResourceManagerTemplateDeployment@3
                  inputs:
                    deploymentScope: 'Subscription'
                    azureResourceManagerConnection: $(subscriptionConnectionName)  #defined in variable
                    subscriptionId: $(subscriptionId) #defined in variable
                    location: $(deploymentLocation) #defined in variable
                    templateLocation: 'Linked artifact'
                    csmFile: '$(Pipeline.Workspace)/resourceTemplates/linked-nested/nested/azure.deploy.json' # path to the file you wan to deploy. could be url using csmFileLink
                    csmParametersFile: '$(Pipeline.Workspace)/resourceTemplates/ci-cd/azure.deploy.parameters.json'
                    deploymentMode: 'Incremental'
                    deploymentName: 'cicd$(Build.BuildNumber)'